=== studentls/MolSimDS/simulationfile.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--

file: simulation.xsd
author: Leonhard Spiegelberg & Florian Dietz

  -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- simple vector, node that this should be later length-checked! -->
  <xsd:simpleType name="Vec3_t">
    <xsd:list itemType="xsd:decimal" ></xsd:list>
  </xsd:simpleType>

  <xsd:simpleType name="dim3_t">
    <xsd:list itemType="xsd:int"></xsd:list>
  </xsd:simpleType>

  <!-- 
  types of algorithms
  -->
  <xsd:complexType name="List_t">
  
  </xsd:complexType>

  <xsd:complexType name="conditions_t">
    <xsd:sequence>
      <xsd:element name="condition" minOccurs="0" maxOccurs="6">
        <xsd:complexType>
          <xsd:simpleContent>
           <xsd:extension base="xsd:string">
             <!--
             possible values are: left, right, top, bottom, front, back, all, outflow, none
             note that if a condition with value "all", "outflow" or "none" appears, all left, right,... 
             conditions will be ignored!
             -->
            <xsd:attribute name="value" type="xsd:string"></xsd:attribute>
           </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>        
      </xsd:element>
    </xsd:sequence>
    
    
  
  </xsd:complexType>
  
  <xsd:complexType name="LinkedCell_t">
    <xsd:all>
      <xsd:element name="sizeofdomainX" type="xsd:decimal"></xsd:element>
      <xsd:element name="sizeofdomainY" type="xsd:decimal"></xsd:element>
      <xsd:element name="sizeofdomainZ" type="xsd:decimal"></xsd:element>
      <xsd:element name="cutoff_radius" type="xsd:decimal"></xsd:element>
      
      <!-- the front lower left corner -->
      <xsd:element name="offset" type="Vec3_t"></xsd:element>
      
      <!-- boundary conditions -->
      <xsd:element name="conditions" type="conditions_t" minOccurs="0" maxOccurs="1"></xsd:element>
      
    </xsd:all>
    
  </xsd:complexType>
  
  <!--
  algorithm complex type
  -->
  <xsd:complexType name="algorithm_t">
    <xsd:choice>
      <xsd:element name="List" type="List_t"></xsd:element>
      <xsd:element name="LinkedCell" type="LinkedCell_t"></xsd:element>
    </xsd:choice>
    
  </xsd:complexType>
  <!-- 
  parameter complex type
  -->
  
  <xsd:complexType name="params_t">
    <xsd:all>
      <xsd:element name="output" type="xsd:string"></xsd:element>
      <xsd:element name="iterationsperoutput" type="xsd:int"></xsd:element>
      <xsd:element name="delta_t" type="xsd:decimal"></xsd:element>
      <xsd:element name="t_end" type="xsd:decimal"></xsd:element>
      <xsd:element name="epsilon" type="xsd:decimal"></xsd:element>
      <xsd:element name="sigma" type="xsd:decimal"></xsd:element>
      <xsd:element name="timestepsPerThermostatApplication" type="xsd:int"></xsd:element>
      <xsd:element name="initialTemperature" type="xsd:decimal"></xsd:element>
      <xsd:element name="targetTemperature" type="xsd:decimal"></xsd:element>
      <xsd:element name="temperatureDifferenceStepSize" type="xsd:decimal"></xsd:element>
      <xsd:element name="t_start" type="xsd:decimal"></xsd:element>
      <xsd:element name="outputfmt">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="None"></xsd:enumeration>
            <xsd:enumeration value="VTK"></xsd:enumeration>
            <xsd:enumeration value="XYZ"></xsd:enumeration>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="algorithm" type="algorithm_t"></xsd:element>
    
    </xsd:all> 
  </xsd:complexType>
  
  
  <!--
  data node stuff
  -->
  
  <xsd:complexType name="particle_t">
    <xsd:all>
      <xsd:element name="X" type="Vec3_t"></xsd:element>
      <xsd:element name="V" type="Vec3_t"></xsd:element>
      <xsd:element name="m" type="xsd:decimal"></xsd:element>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="cuboid_t">
    <xsd:all>
      <xsd:element name="X" type="Vec3_t"></xsd:element>
      <xsd:element name="V" type="Vec3_t"></xsd:element>
      <xsd:element name="N" type="dim3_t"></xsd:element>
      <xsd:element name="h" type="xsd:decimal"></xsd:element>
      <xsd:element name="m" type="xsd:decimal"></xsd:element>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="sphere_t">
    <xsd:all>
      <xsd:element name="X" type="Vec3_t"></xsd:element>
      <xsd:element name="V" type="Vec3_t"></xsd:element>
      <xsd:element name="r" type="xsd:decimal"></xsd:element>
      <xsd:element name="h" type="xsd:decimal"></xsd:element>
      <xsd:element name="m" type="xsd:decimal"></xsd:element>
      <xsd:element name="dimensions" type="xsd:integer"></xsd:element>
    </xsd:all>
  </xsd:complexType>
  
  <xsd:complexType name="data_t">
    <xsd:sequence>
      <xsd:element name="particle" type="particle_t" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="inputfile" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="cuboid" type="cuboid_t" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="sphere" type="sphere_t" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>
 

  <!--
  simulation data type
  -->
  <xsd:complexType name="simulationfile_t">

    <xsd:sequence>
      <xsd:element name="params" type="params_t"></xsd:element>     
      <xsd:element name="data" type="data_t"></xsd:element>
    </xsd:sequence>

  </xsd:complexType>

  <!-- root element
  -->
  <xsd:element name="simulationfile" type="simulationfile_t">   
  </xsd:element>

</xsd:schema>

=== studentls/MolSimDS/smallExp.xml
<?xml version="1.0"?>

<!--

file: Task3.xml everything for Sheet3 
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <gravity>12.44</gravity>
    <timestepsPerThermostatApplication>1000</timestepsPerThermostatApplication>
    <initialTemperature>40.0</initialTemperature>
    <targetTemperature>2.0</targetTemperature>
    <temperatureDifferenceStepSize>0.1</temperatureDifferenceStepSize>
   
    <delta_t>0.0005</delta_t>
    <outputfmt>VTK</outputfmt>
    
    <t_end>25.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <LinkedCell>
        <cutoff_radius>2.5</cutoff_radius>
        <sizeofdomainX>63.0</sizeofdomainX>
        <sizeofdomainY>36.0</sizeofdomainY>
        <sizeofdomainZ>0.0</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="all"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- Liquid1 -->
    <cuboid>
      <epsilon>1.0</epsilon>
      <sigma>1.0</sigma>
      <h>1.2</h>
      <m>1</m>
      <N>50 14 1</N>
      <V>0.0 0.0 0.0</V>
      <X>0.6 2.0 0.0</X>
    </cuboid>

    <!-- Liquid2 -->
    <cuboid>
      <epsilon>1.0</epsilon>
      <sigma>0.9412</sigma>
      <h>1.2</h>
      <m>2</m>
      <N>50 14 1</N>
      <V>0.0 0.0 0.0</V>
      <X>0.6 19.0 0.0</X>
    </cuboid>
  </data>

</simulationfile>

=== studentls/MolSimDS/sphereexample.xml
<?xml version="1.0"?>

<!--

file: example.xml shows usage of the XML Format
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <timestepsPerThermostatApplication>-1</timestepsPerThermostatApplication>
    <initialTemperature>0.0</initialTemperature>
    <targetTemperature>2.0</targetTemperature>
    <temperatureDifferenceStepSize>0.1</temperatureDifferenceStepSize>
   
    <delta_t>0.00005</delta_t>
    <epsilon>5.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>5.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <List></List>
    </algorithm>
    
  </params>

  <data>
    <sphere>
      <dimensions>2</dimensions>
      <h>1.1225</h>
      <m>1.0</m>
      <r>15</r>
      <V>0.0 -10.0 0.0</V>
      <X>60.0 25.0 0.0</X>
    </sphere>
  </data>

</simulationfile>

=== studentls/MolSimDS/xml/PeriodicBoundaries.xml
<?xml version="1.0"?>

<!--

file: PeriodicBoundaries.xml simple test file to simulate periodic boundaries
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <dimension>2</dimension>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <brownianMotionFactor>0.1</brownianMotionFactor>
   
    <delta_t>0.0005</delta_t>
    <epsilon>5.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>30.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <LinkedCell>
        <cutoff_radius>20.0</cutoff_radius>
        <sizeofdomainX>20.0</sizeofdomainX>
        <sizeofdomainY>20.0</sizeofdomainY>
        <sizeofdomainZ>0.0</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="left" type="periodic"></condition> 
          <condition value="right" type="periodic"></condition>
          <condition value="bottom" type="reflective"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- material1-->
    <material epsilon="5.0" sigma="1.0" name="sphereMat"/>
    
    <!-- one single particle -->
    <particle>
      <X>1.4 5.0 0.0</X>
      <V>-10.0 0.0 0.0</V>
      <m>1.0</m>
      <material>sphereMat</material>
    </particle>
   
  </data>

</simulationfile>
