=== studentls/MolSimDS/simulationfile.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--

file: simulation.xsd
author: Leonhard Spiegelberg & Florian Dietz

  -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- simple vector, node that this should be later length-checked! -->
  <xsd:simpleType name="Vec3_t">
    <xsd:list itemType="xsd:decimal" ></xsd:list>
  </xsd:simpleType>

  <xsd:simpleType name="dim3_t">
    <xsd:list itemType="xsd:int"></xsd:list>
  </xsd:simpleType>

  <!-- 
  types of algorithms
  -->
  <xsd:complexType name="List_t">
  
  </xsd:complexType>

  <xsd:complexType name="conditions_t">
    <xsd:sequence>
      <xsd:element name="condition" minOccurs="0" maxOccurs="6">
        <xsd:complexType>
          <xsd:simpleContent>
           <xsd:extension base="xsd:string">
             <!--
             possible values are: left, right, top, bottom, front, back, all, outflow, none
             note that if a condition with value "all", "outflow" or "none" appears, all left, right,... 
             conditions will be ignored!
             -->
            <xsd:attribute name="value" type="xsd:string"></xsd:attribute>
           </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>        
      </xsd:element>
    </xsd:sequence>
    
    
  
  </xsd:complexType>
  
  <xsd:complexType name="LinkedCell_t">
    <xsd:all>
      <xsd:element name="sizeofdomainX" type="xsd:decimal"></xsd:element>
      <xsd:element name="sizeofdomainY" type="xsd:decimal"></xsd:element>
      <xsd:element name="sizeofdomainZ" type="xsd:decimal"></xsd:element>
      <xsd:element name="cutoff_radius" type="xsd:decimal"></xsd:element>
      
      <!-- the front lower left corner -->
      <xsd:element name="offset" type="Vec3_t"></xsd:element>
      
      <!-- boundary conditions -->
      <xsd:element name="conditions" type="conditions_t" minOccurs="0" maxOccurs="1"></xsd:element>
      
    </xsd:all>
    
  </xsd:complexType>
  
  <!--
  algorithm complex type
  -->
  <xsd:complexType name="algorithm_t">
    <xsd:choice>
      <xsd:element name="List" type="List_t"></xsd:element>
      <xsd:element name="LinkedCell" type="LinkedCell_t"></xsd:element>
    </xsd:choice>
    
  </xsd:complexType>
  <!-- 
  parameter complex type
  -->
  
  <xsd:complexType name="params_t">
    <xsd:all>
      <xsd:element name="output" type="xsd:string"></xsd:element>
      <xsd:element name="iterationsperoutput" type="xsd:int"></xsd:element>
      <xsd:element name="delta_t" type="xsd:decimal"></xsd:element>
      <xsd:element name="t_end" type="xsd:decimal"></xsd:element>
      <xsd:element name="epsilon" type="xsd:decimal"></xsd:element>
      <xsd:element name="sigma" type="xsd:decimal"></xsd:element>
      <xsd:element name="timestepsPerThermostatApplication" type="xsd:int"></xsd:element>
      <xsd:element name="initialTemperature" type="xsd:decimal"></xsd:element>
      <xsd:element name="targetTemperature" type="xsd:decimal"></xsd:element>
      <xsd:element name="temperatureDifferenceStepSize" type="xsd:decimal"></xsd:element>
      <xsd:element name="t_start" type="xsd:decimal"></xsd:element>
      <xsd:element name="outputfmt">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="None"></xsd:enumeration>
            <xsd:enumeration value="VTK"></xsd:enumeration>
            <xsd:enumeration value="XYZ"></xsd:enumeration>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="algorithm" type="algorithm_t"></xsd:element>
    
    </xsd:all> 
  </xsd:complexType>
  
  
  <!--
  data node stuff
  -->
  
  <xsd:complexType name="particle_t">
    <xsd:all>
      <xsd:element name="X" type="Vec3_t"></xsd:element>
      <xsd:element name="V" type="Vec3_t"></xsd:element>
      <xsd:element name="m" type="xsd:decimal"></xsd:element>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="cuboid_t">
    <xsd:all>
      <xsd:element name="X" type="Vec3_t"></xsd:element>
      <xsd:element name="V" type="Vec3_t"></xsd:element>
      <xsd:element name="N" type="dim3_t"></xsd:element>
      <xsd:element name="h" type="xsd:decimal"></xsd:element>
      <xsd:element name="m" type="xsd:decimal"></xsd:element>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="sphere_t">
    <xsd:all>
      <xsd:element name="X" type="Vec3_t"></xsd:element>
      <xsd:element name="V" type="Vec3_t"></xsd:element>
      <xsd:element name="r" type="xsd:decimal"></xsd:element>
      <xsd:element name="h" type="xsd:decimal"></xsd:element>
      <xsd:element name="m" type="xsd:decimal"></xsd:element>
      <xsd:element name="dimensions" type="xsd:integer"></xsd:element>
    </xsd:all>
  </xsd:complexType>
  
  <xsd:complexType name="data_t">
    <xsd:sequence>
      <xsd:element name="particle" type="particle_t" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="inputfile" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="cuboid" type="cuboid_t" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      <xsd:element name="sphere" type="sphere_t" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>
 

  <!--
  simulation data type
  -->
  <xsd:complexType name="simulationfile_t">

    <xsd:sequence>
      <xsd:element name="params" type="params_t"></xsd:element>     
      <xsd:element name="data" type="data_t"></xsd:element>
    </xsd:sequence>

  </xsd:complexType>

  <!-- root element
  -->
  <xsd:element name="simulationfile" type="simulationfile_t">   
  </xsd:element>

</xsd:schema>

=== studentls/MolSimDS/listexample.xml
<?xml version="1.0"?>

<!--

file: example.xml shows usage of the XML Format
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <brownianMotionFactor>0.1</brownianMotionFactor>
   
    <delta_t>0.02</delta_t>
    <epsilon>5.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>5.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <List></List>
    </algorithm>
    
  </params>

  <data>
    <inputfile>cuboid.txt</inputfile>
  </data>

</simulationfile>

=== studentls/MolSimDS/FallingDropInitialize.xml
<?xml version="1.0"?>

<!--

file: FallingDrop.xml everything for Sheet4, has to be made!
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <dimension>2</dimension>
    <initialTemperature>40</initialTemperature>
    <iterationsTillThermostatApplication>1000</iterationsTillThermostatApplication>
    <targetTemperature>0.5</targetTemperature>
    <temperatureStepSize>0.2</temperatureStepSize>
    <gravity>-12.44</gravity>
    <output>TXT</output>
    <outputfmt>TXT</outputfmt>
    <iterationsperoutput>1000</iterationsperoutput>
   
    <delta_t>0.0005</delta_t>
    <epsilon>1.0</epsilon>
   
    <sigma>1.2</sigma>
    
    <t_end>15.1</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <LinkedCell>
        <cutoff_radius>2.5</cutoff_radius>
        <sizeofdomainX>303.0</sizeofdomainX>
        <sizeofdomainY>180.0</sizeofdomainY>
        <sizeofdomainZ>0.0</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="all"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- material1-->
    <material epsilon="1.0" sigma="1.2" name="bassinMat" mass="1.0"/>
   
    <!-- C1 -->
    <cuboid>
      <h>1.1225</h>
      <N>250 50 1</N>
      <V>0.0 0.0 0.0</V>
      <X>1.5 2.0 0.0</X>
      <material>bassinMat</material>
    </cuboid>
    
  </data>

</simulationfile>

=== studentls/MolSimDS/Task3.xml
<?xml version="1.0"?>

<!--

file: Task3.xml everything for Sheet3 
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <gravity>0</gravity>
    <timestepsPerThermostatApplication>-1</timestepsPerThermostatApplication>
    <initialTemperature>0.0</initialTemperature>
    <targetTemperature>2.0</targetTemperature>
    <temperatureDifferenceStepSize>0.1</temperatureDifferenceStepSize>
   
    <delta_t>0.0005</delta_t>
    <epsilon>5.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>20.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <LinkedCell>
        <cutoff_radius>3.0</cutoff_radius>
        <sizeofdomainX>180.0</sizeofdomainX>
        <sizeofdomainY>90.0</sizeofdomainY>
        <sizeofdomainZ>0.0</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="all"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- C1 -->
    <cuboid>
      <h>1.1225</h>
      <m>1</m>
      <N>100 20 1</N>
      <V>0.0 0.0 0.0</V>
      <X>20.0 20.0 0.0</X>
    </cuboid>
    
    <!-- C2 -->
    <cuboid>
      <h>1.1225</h>
      <m>1</m>
      <N>20 20 1</N>
      <V>0.0 -10.0 0.0</V>
      <X>70.0 60.0 0.0</X>
    </cuboid>
  </data>

</simulationfile>

=== studentls/MolSimDS/FallingDrop.xml
<?xml version="1.0"?>

<!--

file: FallingDrop.xml everything for Sheet4, has to be made!
author: F.Dietz & L.Spiegelberg

NOTE:
This file exists to fix a problem because FallingDropInitialize was executed when it was bugged. This is no longer the case.
This file can therefore be ignored.

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <dimension>2</dimension>
    <brownianMotionFactor>0.1</brownianMotionFactor>
    <gravity>-12.44</gravity>
    <output>Drop</output>

    <iterationsperoutput>10</iterationsperoutput>

    <delta_t>0.0005</delta_t>
    <epsilon>1.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.2</sigma>

    <t_end>40</t_end>
    <t_start>0.0</t_start>

    <algorithm>
      <LinkedCell>
        <cutoff_radius>2.5</cutoff_radius>
        <sizeofdomainX>303.0</sizeofdomainX>
        <sizeofdomainY>180.0</sizeofdomainY>
        <sizeofdomainZ>0.0</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="all"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>

  </params>

  <data>
    <!-- material1-->
    <material epsilon="1.0" sigma="1.2" name="bassinMat"/>
    
    <!-- the liquid in the bassin -->
    
    <inputfile>TXT_29000.txt</inputfile>
    
    <!-- a drop -->
    <sphere>
      <X>150.0 150.0 0.0</X>
      <V>0.0 0.0 0.0</V>
      <r>20</r>
      <m>1.0</m>
      <h>1.2</h>
      <dimensions>2</dimensions>
      <material>bassinMat</material>
    </sphere>
    
  </data>

</simulationfile>

=== studentls/MolSimDS/xml/ArgonEquilibration.xml
<?xml version="1.0"?>

<!--

file: used to create an equilibrated fluid
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <dimension>3</dimension>
    <output>argoneqnew</output>
    
    <iterationsperoutput>1000</iterationsperoutput>
    <initialTemperature>0.01</initialTemperature>
    <iterationsTillThermostatApplication>40</iterationsTillThermostatApplication>
    <targetTemperature>3.0</targetTemperature>
    <temperatureStepSize>0.001</temperatureStepSize>
   
    <delta_t>0.001</delta_t>
    <epsilon>1.0</epsilon>
    <outputfmt>TXT</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>150.0</t_end>
    <t_start>0.0</t_start>
    <potentialforce>
      <SLJ></SLJ>
    </potentialforce>
    <!--<thermodynamicaldata iterationsTillCalculation="100" iterationsPerCalculation="4" deltat="0.2"></thermodynamicaldata>
   -->
    <algorithm>
      <LinkedCell>
        <cutoff_radius>2.3</cutoff_radius>
        <sizeofdomainX>9.2</sizeofdomainX>
        <sizeofdomainY>9.2</sizeofdomainY>
        <sizeofdomainZ>9.2</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="front" type="periodic"></condition>
          <condition value="back" type="periodic"></condition>
          <condition value="left" type="periodic"></condition>
          <condition value="right" type="periodic"></condition>
          <condition value="top" type="periodic"></condition>
          <condition value="bottom" type="periodic"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- material1-->
    <material epsilon="1.0" sigma="1.0" name="Liquid1" mass="1.0"/>
    
    <!-- C1 -->
    <cuboid>
      <h>1.15</h>
      <N>8 8 8</N>
      <V>0.0 0.0 0.0</V>
      <X>0.575 0.575 0.575</X>
      <material>Liquid1</material>
    </cuboid>
    
  </data>

</simulationfile>

=== studentls/MolSimDS/xml/ArgonCooling.xml
<?xml version="1.0"?>

<!--

file: used to perform cooling experiment
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <dimension>3</dimension>
    <output>argoncooling</output>
    
    <iterationsperoutput>100</iterationsperoutput>
    <initialTemperature>3.0</initialTemperature>
    <iterationsTillThermostatApplication>50</iterationsTillThermostatApplication>
    <targetTemperature>0.5</targetTemperature>
    <temperatureStepSize>-0.00078</temperatureStepSize>
   
    <delta_t>0.001</delta_t>
    <epsilon>1.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>250.0</t_end>
    <t_start>0.0</t_start>
    <potentialforce>
      <SLJ></SLJ>
    </potentialforce>
    <thermodynamicaldata iterationsTillCalculation="1000" iterationsPerCalculation="5" deltat="0.2"></thermodynamicaldata>
   
    <algorithm>
      <LinkedCell>
        <cutoff_radius>2.3</cutoff_radius>
        <sizeofdomainX>9.2</sizeofdomainX>
        <sizeofdomainY>9.2</sizeofdomainY>
        <sizeofdomainZ>9.2</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="front" type="reflective"></condition>
          <condition value="back" type="reflective"></condition>
          <condition value="left" type="periodic"></condition>
          <condition value="right" type="periodic"></condition>
          <condition value="top" type="periodic"></condition>
          <condition value="bottom" type="periodic"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- material1-->
    <material epsilon="1.0" sigma="1.0" name="Liquid1" mass="1.0"/>
    
    <!-- use txt inputfile -->
    <inputfile>argoneq.txt</inputfile>
    
  </data>

</simulationfile>

=== studentls/MolSimDS/example.xml
<?xml version="1.0"?>

<!--

file: example.xml shows usage of the XML Format
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <brownianMotionFactor>0.1</brownianMotionFactor>
   
    <delta_t>0.02</delta_t>
    <epsilon>5.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.0</sigma>
    
    <t_end>5.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <LinkedCell>
        <cutoff_radius>3.0</cutoff_radius>
        <sizeofdomainX>180.0</sizeofdomainX>
        <sizeofdomainY>90.0</sizeofdomainY>
        <sizeofdomainZ>0.0</sizeofdomainZ>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <inputfile>cuboid.txt</inputfile>
  </data>

</simulationfile>

=== studentls/MolSimDS/xml/RayleighTaylor3D.xml
<?xml version="1.0"?>

<!--

file: ThermostatBig.xml big experiment for Thermostat functionality
author: F.Dietz & L.Spiegelberg

-->

<simulationfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationfile.xsd">

  <params>
    <dimension>3</dimension>
    <output>out</output>
    
    <iterationsperoutput>10</iterationsperoutput>
    <initialTemperature>40</initialTemperature>
    <iterationsTillThermostatApplication>1000</iterationsTillThermostatApplication>
    <targetTemperature>40</targetTemperature>
    <temperatureStepSize>0.1</temperatureStepSize>
    <gravity>-12.44</gravity>
   
    <delta_t>0.0005</delta_t>
    <epsilon>2.0</epsilon>
    <outputfmt>VTK</outputfmt>
    <sigma>1.15</sigma>
    
    <t_end>100.0</t_end>
    <t_start>0.0</t_start>
    
    <algorithm>
      <LinkedCell>
        <cutoff_radius>2.5</cutoff_radius>
        <sizeofdomainX>60.0</sizeofdomainX>
        <sizeofdomainY>24.0</sizeofdomainY>
        <sizeofdomainZ>51.0</sizeofdomainZ>
        <offset>0.0 0.0 0.0</offset>
        <conditions>
          <condition value="front" type="reflective"></condition>
          <condition value="back" type="reflective"></condition>
          <condition value="left" type="periodic"></condition>
          <condition value="right" type="periodic"></condition>
          <condition value="top" type="periodic"></condition>
          <condition value="bottom" type="periodic"></condition>
        </conditions>
      </LinkedCell>
    </algorithm>
    
  </params>

  <data>
    <!-- material1-->
    <material epsilon="2.0" sigma="1.15" name="Liquid1" mass="40.0"/>
    <!-- material1-->
    <material epsilon="2.0" sigma="1.15" name="Liquid2" mass="80.0"/>
    
    <!-- C1 -->
    <cuboid>
      <h>1.2</h>
      <N>48 9 42</N>
      <V>0.0 0.0 0.0</V>
      <X>0.6 0.6 0.6</X>
      <material>Liquid1</material>
    </cuboid>
    
    <!-- C2 -->
    <cuboid>
      <h>1.2</h>
      <N>48 9 42</N>
      <V>0.0 0.0 0.0</V>
      <X>0.6 11.4 0.6</X>
      <material>Liquid2</material>
    </cuboid>
    
  </data>

</simulationfile>
